import Navbar from "@/components/dashboard/navbar";
import Sidebar from "@/components/dashboard/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="m-4 grid grid-cols-8 gap-4">
            <Sidebar/>
            <div className="col-span-6">
                <Navbar/>
                {children}
            </div>
        </div>
      </body>
    </html>
  );
}
